"""dubl

Revision ID: d016e24ce4be
Revises: 
Create Date: 2023-07-08 22:10:16.303364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d016e24ce4be"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "new",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("utl", sa.String(), nullable=True),
        sa.Column("date_of_hew", sa.DateTime(), nullable=True),
        sa.Column("date_of_save", sa.DateTime(), nullable=True),
        sa.Column("date_of_change", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("new")
    # ### end Alembic commands ###
