version: '3.9'
services:
  worker:
    restart: always
    build: ./app
    command: celery --app worker.app worker --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
  api:
    restart: always
    build: ./app
    command: gunicorn api.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80 #uvicorn api.main:app --host 0.0.0.0 --port 80
    env_file:
      - .env
    depends_on:
      - postgres
  worker-beat:
    restart: always
    build: ./app
    command: celery --app worker.app beat -l info
    env_file:
      - .env
    depends_on:
      - worker  
  redis:
    restart: always
    image: redis:7.0-alpine
  postgres:
    restart: always
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres-data: